"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Badge, Button, Card, DisclaimerNote, EmptyState, PageHeader } from "@/components/ui";

interface Reco { id: number; kind: string; topic: string; reason: string | null; guidance: string | null; source_key: string | null; priority: string; confidence: number | null }
interface Suggestion { risk_area: string; specialty: string; confidence: number; reason: string }
interface Source { key: string; title: string; publisher: string | null; version: string | null }

export default function RecommendationsPage() {
  const qc = useQueryClient();
  const recos = useQuery<Reco[]>({ queryKey: ["recommendations"], queryFn: () => api("/recommendations") });
  const specialists = useQuery<{ suggestions: Suggestion[] }>({ queryKey: ["specialists"], queryFn: () => api("/insights/specialists") });
  const sources = useQuery<Source[]>({ queryKey: ["sources"], queryFn: () => api("/sources") });

  async function refreshEngine() {
    await api("/recommendations/refresh", { method: "POST" });
    qc.invalidateQueries({ queryKey: ["recommendations"] });
    qc.invalidateQueries({ queryKey: ["specialists"] });
  }

  return (
    <>
      <PageHeader
        title="Health Insights"
        subtitle="Preventive-care topics generated from your records and validated public-health rules"
        action={<Button onClick={refreshEngine}>Refresh analysis</Button>}
      />

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="space-y-4 lg:col-span-2">
          {!recos.data?.length ? (
            <EmptyState message="No active insights right now."
                        hint="Add family history or measurements, then refresh the analysis." />
          ) : (
            recos.data.map((r) => (
              <Card key={r.id}>
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h2 className="font-semibold capitalize text-slate-900">{r.topic.replace(/_/g, " ")}</h2>
                  <div className="flex items-center gap-2">
                    <Badge tone={r.priority === "high" ? "red" : r.priority === "medium" ? "amber" : "slate"}>{r.priority} priority</Badge>
                    <button aria-label="Dismiss this insight"
                            className="text-xs font-semibold text-slate-400 hover:text-red-500"
                            onClick={async () => {
                              await api(`/recommendations/${r.id}`, { method: "DELETE" });
                              qc.invalidateQueries({ queryKey: ["recommendations"] });
                            }}>
                      Dismiss
                    </button>
                  </div>
                </div>
                <p className="mt-2 text-sm leading-relaxed text-slate-600">{r.guidance}</p>
                {r.reason && <p className="mt-2 text-xs leading-relaxed text-slate-500"><strong>Why:</strong> {r.reason}</p>}
                {r.source_key && (
                  <p className="mt-2 text-[11px] text-slate-400">
                    Based on rule source: <span className="font-mono">{r.source_key}</span>
                  </p>
                )}
              </Card>
            ))
          )}

          <DisclaimerNote>
            These topics are generated by deterministic rules from validated public-health guidance
            applied to information you entered. They are suggestions for discussion with a qualified
            healthcare professional — not diagnoses, prescriptions, or medical orders.
          </DisclaimerNote>
        </div>

        <div className="space-y-4">
          <Card title="Specialty discussion suggestions">
            {!specialists.data?.suggestions.length ? (
              <p className="text-sm text-slate-400">Nothing to suggest yet.</p>
            ) : (
              <ul className="space-y-3">
                {specialists.data.suggestions.map((s) => (
                  <li key={s.specialty + s.risk_area} className="rounded-lg bg-brand-50 p-3">
                    <p className="text-sm font-bold text-brand-900">{s.specialty}</p>
                    <p className="mt-1 text-xs leading-relaxed text-slate-600">{s.reason}</p>
                  </li>
                ))}
              </ul>
            )}
          </Card>

          <Card title="Knowledge sources">
            <ul className="space-y-2.5 text-xs">
              {(sources.data ?? []).map((s) => (
                <li key={s.key} className="rounded-lg border border-slate-100 p-2.5">
                  <p className="font-semibold text-slate-700">{s.title}</p>
                  <p className="mt-0.5 text-slate-400">{s.publisher}{s.version && ` · v${s.version}`}</p>
                </li>
              ))}
            </ul>
          </Card>
        </div>
      </div>
    </>
  );
}
