"""GenAI repair report generator.

Produces a "Road Damage Assessment" markdown report. If the LLM is unavailable
a deterministic template is used with the same structured data, so numbers are
always backend-originated and never hallucinated.
"""
from __future__ import annotations

import json
from typing import Any

from app.ai.genai.llm_service import llm_service, sanitize
from app.ai.genai.prompt_manager import REPORT_SYSTEM_PROMPT, REPORT_USER_TEMPLATE


def _fmt_inr(value: float | None) -> str:
    if value is None:
        return "-"
    return f"₹{value:,.2f}"


def template_report(data: dict[str, Any]) -> str:
    p = data
    lines = [
        "# Road Damage Assessment",
        "",
        f"**Pothole ID:** {p.get('pothole_code') or p.get('id')}",
        f"**Generated by:** RoadGuard AI (template mode - LLM unavailable)",
        "",
        "## 1. Problem Summary",
        f"A pothole was detected with {p.get('confidence', 0) * 100:.1f}% AI confidence. "
        f"Its current status is {p.get('status', 'UNKNOWN')}.",
        "",
        "## 2. Location",
        f"{p.get('road') or 'Road not specified'}, Ward {p.get('ward') or '-'}, "
        f"{p.get('city') or '-'}, {p.get('district') or '-'}, {p.get('state') or '-'}.",
        f"Coordinates: {p.get('latitude', '-')}, {p.get('longitude', '-')}",
        "",
        "## 3. AI Detection",
        f"- Detection confidence: **{p.get('confidence', 0) * 100:.1f}%**",
        f"- Analysis mode: **{p.get('ai_mode', 'demo')}**",
        "",
        "## 4. Severity",
        f"- Severity: **{p.get('severity', '-')}** (score {p.get('severity_score', 0):.0f}/100)",
        f"- Note: {p.get('severity_note', 'Estimated severity for triage; engineering assessment required.')}",
        "",
        "## 5. Estimated Area",
        f"- Estimated affected area: **{p.get('estimated_area', 0)} m²** "
        "(estimated from image; RGB images cannot give exact physical dimensions without calibration).",
        "",
        "## 6. Recommended Repair Area",
        f"- Recommended repair area (with margin): **{p.get('repair_area', 0)} m²** "
        "(configurable repair margin, not an official engineering rule).",
        "",
        "## 7. Cost Estimate",
        f"- Estimated repair cost: **{_fmt_inr(p.get('estimated_cost'))}**",
        f"- Breakdown: {json.dumps(p.get('cost_breakdown', {}), indent=2)}",
        "- This is an **AI-assisted preliminary estimate**. Actual cost is recorded after repair.",
        "",
        "## 8. Recommended Action",
        f"- Recommended action: {p.get('recommended_action', 'Schedule repair based on priority.')}",
        "",
        "## 9. Priority",
        f"- Priority: **{p.get('priority', '-')}** (score {p.get('priority_score', 0):.0f}/100)",
        "",
        "## 10. Limitations",
        "1. RGB images do not provide reliable physical depth without additional information.",
        "2. Cost estimates are preliminary and configurable.",
        "3. AI detection can produce false positives/negatives.",
        "4. Government engineering verification is still required.",
        "5. These recommendations are not a substitute for professional engineering inspection.",
        "",
    ]
    return "\n".join(lines)


def generate_repair_report(data: dict[str, Any]) -> dict:
    """Generate a report. Always returns {report, used_llm}."""
    safe = sanitize(data)
    result = llm_service.complete(
        REPORT_SYSTEM_PROMPT,
        REPORT_USER_TEMPLATE.format(data=json.dumps(safe)),
    )
    if result["used_llm"]:
        return {"report": result["text"], "used_llm": True}
    return {"report": template_report(safe), "used_llm": False}
