"""initial schema

Revision ID: d854635822aa
Revises: 
Create Date: 2026-08-24 22:46:24.501592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd854635822aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('last_reviewed', sa.String(length=32), nullable=True),
    sa.Column('jurisdiction', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditions_name'), ['name'], unique=True)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'caregiver', 'professional', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('clinical_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=128), nullable=False),
    sa.Column('population', sa.String(length=128), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority', native_enum=False, length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('last_reviewed', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_key'], ['clinical_sources.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    with op.batch_alter_table('clinical_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_rules_condition'), ['condition'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index('ix_consents_user_type', ['user_id', 'consent_type'], unique=False)

    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_logs_logged_on'), ['logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_diet_logs_user_id'), ['user_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('clinic', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_family_doctor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctor_name', 'clinic', name='uq_user_doctor')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=128), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=16), nullable=True),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_logs_performed_on'), ['performed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_logs_user_id'), ['user_id'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('living_status', sa.Enum('living', 'deceased', 'unknown', name='livingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('relevant_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    op.create_table('health_metric_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('secondary_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_metric_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metric_values_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metric_values_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metric_values_user_id'), ['user_id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_metric')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('health_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('report_uploaded', 'report_analyzed', 'lab_result', 'measurement', 'doctor_visit', 'condition_added', 'medication_added', 'family_history', 'lifestyle', 'recommendation', 'reminder', name='timelineeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_timeline_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_timeline_user_date', ['user_id', 'event_date'], unique=False)

    op.create_table('lifestyle_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('sleep_goal_hours', sa.Float(), nullable=True),
    sa.Column('diet_type', sa.String(length=32), nullable=True),
    sa.Column('goal', sa.String(length=32), nullable=True),
    sa.Column('smoking_status', sa.String(length=16), nullable=True),
    sa.Column('alcohol_frequency', sa.String(length=16), nullable=True),
    sa.Column('stress_level', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifestyle_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifestyle_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('laboratory', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'analyzing', 'complete', 'failed', name='reportstatus', native_enum=False, length=16), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_user_id'), ['user_id'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_on', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('preventive_care', 'specialty_discussion', 'lifestyle', 'trend_followup', name='recommendationkind', native_enum=False, length=32), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority', native_enum=False, length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_reco_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence', sa.Enum('none_', 'daily', 'weekly', 'monthly', name='reminderrecurrence', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_logs_logged_on'), ['logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('diagnosed_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'condition_id', name='uq_user_condition')
    )
    with op.batch_alter_table('user_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_conditions_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('diet_preferences', sa.String(length=64), nullable=True),
    sa.Column('exercise_preferences', sa.Text(), nullable=True),
    sa.Column('emergency_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('safety_filtered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index('ix_ai_msg_conversation', ['conversation_id'], unique=False)

    op.create_table('document_processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_report_id'), ['report_id'], unique=False)

    op.create_table('family_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('diagnosis_age', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_conditions_member_id'), ['member_id'], unique=False)

    op.create_table('family_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_a_id', sa.Integer(), nullable=False),
    sa.Column('member_b_id', sa.Integer(), nullable=False),
    sa.Column('relation_of_a_to_b', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_a_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_b_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_relationships_user_id'), ['user_id'], unique=False)

    op.create_table('medical_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('abnormal_flag', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_report_name', ['report_id', 'test_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_entities_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_entities_test_name'), ['test_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_entities_test_name'))
        batch_op.drop_index(batch_op.f('ix_medical_entities_report_id'))
        batch_op.drop_index('ix_entities_report_name')

    op.drop_table('medical_entities')
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_relationships_user_id'))

    op.drop_table('family_relationships')
    with op.batch_alter_table('family_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_conditions_member_id'))

    op.drop_table('family_conditions')
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_report_id'))

    op.drop_table('document_processing_jobs')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_msg_conversation')

    op.drop_table('ai_messages')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('user_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_conditions_user_id'))

    op.drop_table('user_conditions')
    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_sleep_logs_logged_on'))

    op.drop_table('sleep_logs')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))

    op.drop_table('reminders')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.drop_index('ix_reco_user_created')

    op.drop_table('recommendations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_user_id'))

    op.drop_table('medications')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_status'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_category'))

    op.drop_table('medical_reports')
    with op.batch_alter_table('lifestyle_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifestyle_profiles_user_id'))

    op.drop_table('lifestyle_profiles')
    with op.batch_alter_table('health_timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_user_date')
        batch_op.drop_index(batch_op.f('ix_health_timeline_events_user_id'))

    op.drop_table('health_timeline_events')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_metrics_key'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('health_metric_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metric_values_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_metric_values_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_metric_values_metric_key'))

    op.drop_table('health_metric_values')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_logs_performed_on'))

    op.drop_table('exercise_logs')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_user_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('diet_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_diet_logs_logged_on'))

    op.drop_table('diet_logs')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consents_user_type')

    op.drop_table('consents')
    with op.batch_alter_table('clinical_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_rules_condition'))

    op.drop_table('clinical_rules')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('hospitals')
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_name'))

    op.drop_table('conditions')
    op.drop_table('clinical_sources')
    # ### end Alembic commands ###
